services:
    polidog_ssr.event_listener.template_listener:
        class: Polidog\SsrBundle\EventListener\SsrRenderSubscriber
        arguments:
            - "@polidog_ssr.render.ssr_render"
            - "@polidog_ssr.render.cache_ssr_render"
        tags:
            - { name: kernel.event_subscriber }
        private: true

    polidog_ssr.simple_cache:
        class: Symfony\Component\Cache\Simple\Psr6Cache
        arguments:
            - "@cache.app"
        private: true

    polidog_ssr.baracore:
        class: Koriym\Baracoa\Baracoa
        arguments:
            - "%polidog_ssr.bundle_src_path%"
            - "@polidog_ssr.baracore.exception_handler"
        private: true

    polidog_ssr.cache_baracore:
        class: Koriym\Baracoa\CacheBaracoa
        arguments:
            - "%polidog_ssr.bundle_src_path%"
            - "@polidog_ssr.baracore.exception_handler"
            - "@polidog_ssr.simple_cache"
        private: true

    polidog_ssr.baracore.exception_handler:
        class: Koriym\Baracoa\ExceptionHandler

    polidog_ssr.render.ssr_render:
        class: Polidog\SsrBundle\Render\SsrRender
        arguments:
            - "@=container.get(parameter('polidog_ssr.baracoa.object'))"
        private: true

    polidog_ssr.render.cache_ssr_render:
        class: Polidog\SsrBundle\Render\SsrRender
        arguments:
            - "@=container.get(parameter('polidog_ssr.baracoa.cache_object'))"
        private: true
