language: php
php:
  - 7.1
  - hhvm
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
before_script:
  - composer self-update
  - composer global require hirak/prestissimo
  - composer install
script:
  - vender/bin/phpunit